import { DealStatus } from "./types"
import type { Contact, Message, Call, Email, Tag, Activity, Deal } from "./types"

const mockTags: Tag[] = [
  { id: "tag-1", name: "Hot Lead", color: "red" },
  { id: "tag-2", name: "Follow Up", color: "blue" },
  { id: "tag-3", name: "Investor", color: "green" },
  { id: "tag-4", name: "First Time Buyer", color: "purple" },
  { id: "tag-5", name: "Seller", color: "orange" },
]

export const mockContacts: Contact[] = [
  {
    id: "1",
    firstName: "Alice",
    lastName: "Smith",
    llcName: "Alice Holdings LLC",
    phone1: "123-456-7890",
    email1: "alice.smith@example.com",
    propertyAddress: "123 Main St",
    city: "Anytown",
    state: "CA",
    propertyCounty: "Any County",
    propertyType: "Single Family",
    bedrooms: 3,
    totalBathrooms: 2.5,
    buildingSqft: 1800,
    effectiveYearBuilt: 1990,
    estValue: 500000,
    estEquity: 300000,
    dnc: false,
    notes: "Client is very interested in selling quickly. Prefers text communication.",
    dealStatus: DealStatus.LEAD,
    avatarUrl: "/placeholder.svg?height=80&width=80",
    createdAt: "2023-01-15T10:00:00Z",
    updatedAt: "2023-01-15T10:00:00Z",
  },
  {
    id: "2",
    firstName: "Bob",
    lastName: "Johnson",
    llcName: null,
    phone1: "098-765-4321",
    email1: "bob.j@example.com",
    propertyAddress: "456 Oak Ave",
    city: "Anytown",
    state: "CA",
    propertyCounty: "Any County",
    propertyType: "Duplex",
    bedrooms: 4,
    totalBathrooms: 3,
    buildingSqft: 2500,
    effectiveYearBuilt: 2005,
    estValue: 750000,
    estEquity: 350000,
    dnc: true,
    dncReason: "Requested no calls",
    notes: "Looking for investment properties. Prefers email.",
    dealStatus: DealStatus.QUALIFIED,
    avatarUrl: "/placeholder.svg?height=80&width=80",
    createdAt: "2023-02-20T11:30:00Z",
    updatedAt: "2023-02-20T11:30:00Z",
  },
  {
    id: "3",
    firstName: "Charlie",
    lastName: "Brown",
    llcName: null,
    phone1: "111-222-3333",
    email1: "charlie.b@example.com",
    propertyAddress: "789 Pine Ln",
    city: "Otherville",
    state: "NY",
    propertyCounty: "Other County",
    propertyType: "Triplex",
    bedrooms: 6,
    totalBathrooms: 4,
    buildingSqft: 3200,
    effectiveYearBuilt: 1985,
    estValue: 900000,
    estEquity: 400000,
    dnc: false,
    notes: "First time home buyer, needs guidance.",
    dealStatus: DealStatus.PROPOSAL,
    avatarUrl: "/placeholder.svg?height=80&width=80",
    createdAt: "2023-03-01T09:00:00Z",
    updatedAt: "2023-03-01T09:00:00Z",
  },
  {
    id: "4",
    firstName: "Diana",
    lastName: "Prince",
    llcName: "Prince Properties",
    phone1: "444-555-6666",
    email1: "diana.p@example.com",
    propertyAddress: "101 Cedar Rd",
    city: "Anytown",
    state: "CA",
    propertyCounty: "Any County",
    propertyType: "Quadplex",
    bedrooms: 8,
    totalBathrooms: 5,
    buildingSqft: 4000,
    effectiveYearBuilt: 2010,
    estValue: 1200000,
    estEquity: 500000,
    dnc: false,
    notes: "Experienced seller, looking to offload multiple properties.",
    dealStatus: DealStatus.NEGOTIATION,
    avatarUrl: "/placeholder.svg?height=80&width=80",
    createdAt: "2023-04-05T14:00:00Z",
    updatedAt: "2023-04-05T14:00:00Z",
  },
  {
    id: "5",
    firstName: "Eve",
    lastName: "Adams",
    llcName: null,
    phone1: "777-888-9999",
    email1: "eve.a@example.com",
    propertyAddress: "222 Birch Blvd",
    city: "Anytown",
    state: "CA",
    propertyCounty: "Any County",
    propertyType: "Multi Family 5+",
    bedrooms: 10,
    totalBathrooms: 6,
    buildingSqft: 5000,
    effectiveYearBuilt: 1975,
    estValue: 1500000,
    estEquity: 700000,
    dnc: false,
    notes: "High net worth individual, interested in large scale investments.",
    dealStatus: DealStatus.NEGOTIATION,
    avatarUrl: "/placeholder.svg?height=80&width=80",
    createdAt: "2023-05-10T09:45:00Z",
    updatedAt: "2023-05-10T09:45:00Z",
  },
  {
    id: "6",
    firstName: "Frank",
    lastName: "White",
    llcName: null,
    phone1: "123-123-1234",
    email1: "frank.w@example.com",
    propertyAddress: "333 Elm St",
    city: "Otherville",
    state: "NY",
    propertyCounty: "Other County",
    propertyType: "Single Family",
    bedrooms: 4,
    totalBathrooms: 2,
    buildingSqft: 2200,
    effectiveYearBuilt: 2015,
    estValue: 600000,
    estEquity: 450000,
    dnc: false,
    notes: "Recently inherited property, unsure about selling.",
    dealStatus: DealStatus.CLOSED_WON,
    avatarUrl: "/placeholder.svg?height=80&width=80",
    createdAt: "2023-06-01T16:00:00Z",
    updatedAt: "2023-06-01T16:00:00Z",
  },
  {
    id: "7",
    firstName: "Grace",
    lastName: "Taylor",
    llcName: null,
    phone1: "555-111-2222",
    email1: "grace.t@example.com",
    propertyAddress: "444 Poplar Dr",
    city: "Anytown",
    state: "CA",
    propertyCounty: "Any County",
    propertyType: "Duplex",
    bedrooms: 5,
    totalBathrooms: 3.5,
    buildingSqft: 2800,
    effectiveYearBuilt: 1998,
    estValue: 800000,
    estEquity: 300000,
    dnc: true,
    dncReason: "Already purchased",
    notes: "No longer interested.",
    dealStatus: DealStatus.CLOSED_LOST,
    avatarUrl: "/placeholder.svg?height=80&width=80",
    createdAt: "2023-08-01T18:00:00Z",
    updatedAt: "2023-08-01T18:00:00Z",
  },
  {
    id: "8",
    firstName: "Henry",
    lastName: "Miller",
    llcName: "Miller Investments",
    phone1: "222-333-4444",
    email1: "henry.m@example.com",
    propertyAddress: "555 Maple Ave",
    city: "Otherville",
    state: "NY",
    propertyCounty: "Other County",
    propertyType: "Single Family",
    bedrooms: 3,
    totalBathrooms: 2,
    buildingSqft: 1900,
    effectiveYearBuilt: 2002,
    estValue: 550000,
    estEquity: 300000,
    dnc: false,
    notes: "Investor looking for a flip.",
    dealStatus: DealStatus.CLOSED_WON,
    avatarUrl: "/placeholder.svg?height=80&width=80",
    createdAt: "2023-09-15T11:20:00Z",
    updatedAt: "2023-09-15T11:20:00Z",
  },
  {
    id: "9",
    firstName: "Ivy",
    lastName: "Clark",
    llcName: null,
    phone1: "333-444-5555",
    email1: "ivy.c@example.com",
    propertyAddress: "666 Spruce St",
    city: "Anytown",
    state: "CA",
    propertyCounty: "Any County",
    propertyType: "Multi Family 5+",
    bedrooms: 12,
    totalBathrooms: 8,
    buildingSqft: 6000,
    effectiveYearBuilt: 2018,
    estValue: 2500000,
    estEquity: 1000000,
    dnc: false,
    notes: "Looking for commercial investment.",
    dealStatus: DealStatus.CLOSED_WON,
    avatarUrl: "/placeholder.svg?height=80&width=80",
    createdAt: "2023-10-01T08:00:00Z",
    updatedAt: "2023-10-01T08:00:00Z",
  },
  {
    id: "10",
    firstName: "Jack",
    lastName: "Lewis",
    llcName: null,
    phone1: "666-777-8888",
    email1: "jack.l@example.com",
    propertyAddress: "777 Willow Way",
    city: "Otherville",
    state: "NY",
    propertyCounty: "Other County",
    propertyType: "Single Family",
    bedrooms: 4,
    totalBathrooms: 3,
    buildingSqft: 2400,
    effectiveYearBuilt: 1995,
    estValue: 650000,
    estEquity: 350000,
    dnc: false,
    notes: "Needs to sell before buying a new home.",
    dealStatus: DealStatus.LEAD,
    avatarUrl: "/placeholder.svg?height=80&width=80",
    createdAt: "2023-11-20T13:00:00Z",
    updatedAt: "2023-11-20T13:00:00Z",
  },
]

const mockMessages: Message[] = [
  {
    id: "msg-1",
    contactId: "1",
    text: "Hi, is this still available?",
    createdAt: "2024-01-15T10:00:00Z",
    isInbound: false,
  },
  {
    id: "msg-2",
    contactId: "1",
    text: "Yes, it is! What are you interested in?",
    createdAt: "2024-01-15T10:05:00Z",
    isInbound: true,
  },
  {
    id: "3",
    contactId: "2",
    text: "Hello Bob, checking in on the Oak Ave property.",
    createdAt: "2024-01-16T11:00:00Z",
    isInbound: false,
  },
]

const mockCalls: Call[] = [
  {
    id: "call-1",
    contactId: "1",
    duration: 120,
    createdAt: "2024-01-14T09:30:00Z",
    direction: "outbound",
    notes: "Discussed property details and current market value.",
  },
  {
    id: "call-2",
    contactId: "2",
    duration: 300,
    createdAt: "2024-01-15T14:00:00Z",
    direction: "inbound",
    notes: "Bob called to inquire about investment opportunities.",
  },
]

const mockEmails: Email[] = [
  {
    id: "email-1",
    contactId: "1",
    subject: "Property Inquiry - 123 Main St",
    content: "Dear Alice, following up on our conversation...",
    createdAt: "2024-01-13T16:00:00Z",
    isRead: true,
    isSent: false,
  },
  {
    id: "email-2",
    contactId: "2",
    subject: "Investment Opportunities",
    content: "Hi Bob, here are some properties that might interest you...",
    createdAt: "2024-01-15T15:30:00Z",
    isRead: false,
    isSent: true,
  },
]

const mockActivities: Activity[] = [
  {
    id: "activity-1",
    contactId: "1",
    type: "task",
    title: "Prepare offer for Alice Smith",
    description: "Draft a competitive cash offer for 123 Main St.",
    dueDate: "2024-01-18T17:00:00Z",
    status: "pending",
    createdAt: "2024-01-15T11:00:00Z",
  },
  {
    id: "activity-2",
    contactId: "2",
    type: "call",
    title: "Call Bob Johnson about new listings",
    description: "Discuss new duplexes available in his target area.",
    dueDate: "2024-01-17T10:00:00Z",
    status: "pending",
    createdAt: "2024-01-16T09:00:00Z",
  },
  {
    id: "activity-3",
    contactId: "1",
    type: "meeting",
    title: "Meeting with Alice Smith",
    description: "In-person meeting to present offer.",
    dueDate: "2024-01-20T14:00:00Z",
    status: "pending",
    createdAt: "2024-01-16T15:00:00Z",
  },
  {
    id: "activity-4",
    contactId: "1",
    type: "note",
    title: "Initial contact notes",
    description: "Alice is motivated to sell due to relocation. Prefers quick closing.",
    dueDate: "2024-01-15T10:30:00Z",
    status: "completed",
    createdAt: "2024-01-15T10:30:00Z",
    completedAt: "2024-01-15T10:30:00Z",
  },
]

const mockDeals: Deal[] = [
  {
    id: "1",
    contactId: "1",
    deal_name: "123 Main St Acquisition",
    amount: 500000,
    stage: DealStatus.LEAD,
    close_date: "2024-02-28T00:00:00Z",
    createdAt: "2024-01-15T10:00:00Z",
    updatedAt: "2024-01-15T10:00:00Z",
    stage_history: [{ stage_id: DealStatus.LEAD, entered_at: "2024-01-15T10:00:00Z" }],
  },
  {
    id: "2",
    contactId: "2",
    deal_name: "456 Oak Ave Investment",
    amount: 750000,
    stage: DealStatus.QUALIFIED,
    close_date: "2024-03-15T00:00:00Z",
    createdAt: "2024-01-16T11:00:00Z",
    updatedAt: "2024-01-16T11:00:00Z",
    stage_history: [{ stage_id: DealStatus.QUALIFIED, entered_at: "2024-01-16T11:00:00Z" }],
  },
]

export const getContacts = () => [...mockContacts]
export const getMessages = () => [...mockMessages]
export const getCalls = () => [...mockCalls]
export const getEmails = () => [...mockEmails]
export const getActivities = () => [...mockActivities]
export const getDeals = () => [...mockDeals]
export const getTags = () => [...mockTags]

export const getMessagesByContactId = (contactId: string) => mockMessages.filter((msg) => msg.contactId === contact_id)
export const getCallsByContactId = (contactId: string) => mockCalls.filter((call) => call.contactId === contact_id)
export const getEmailsByContactId = (contactId: string) => mockEmails.filter((email) => email.contactId === contact_id)
export const getActivitiesByContactId = (contactId: string) =>
  mockActivities.filter((activity) => activity.contactId === contact_id)
export const getDealsByContactId = (contactId: string) => mockDeals.filter((deal) => deal.contactId === contact_id)
